openapi: 3.0.2
info:
  title: shurl API
  description: A simple URL shortening API
  version: '1.0'
servers:
  - url: https://127.0.1.1:8000
    description: API server
paths:
  /urls:
    get:
      summary: Get all URLs
      responses:
        '200':
          description: OK
    post:
      summary: Create a new URL
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateURLRequest'
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
  /urls/{slug}:
    get:
      summary: Get a specific URL
      parameters:
        - name: slug
          in: path
          required: true
          schema:
            type: string
      responses:
        '302':
          description: Found
        '404':
          description: Not Found
  /docs:
    get:
      summary: Get the OpenAPI specification
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenAPISpecification'
components:
  schemas:
    CreateURLRequest:
      type: object
      properties:
        long_url:
          type: string
        custom_slug:
          type: string
    OpenAPISpecification:
      type: object
