name: Django CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug environment variables
        run: env

      - name: Set up Docker Compose
        run: |
          docker-compose --version

      - name: Build and start containers
        run: |
          docker-compose up --build --detach

      - name: Run migrations
        run: |
          docker-compose exec web python manage.py migrate

      - name: Run tests
        run: |
          docker-compose exec web python manage.py test

      - name: Tear down
        run: |
          docker-compose down
